services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    network_mode: host
    volumes:
      - ./homeassistant:/config
    restart: unless-stopped

  mosquitto:
    image: eclipse-mosquitto
    container_name: mqtt
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto:/mosquitto
    restart: unless-stopped